name: App Support Request
description: Report an issue or request help with one of our iOS apps
labels: ["support"]
body:
  - type: dropdown
    id: app
    attributes:
      label: Which app?
      description: Select the app this is about
      options:
        - SplitSmart
        - Other / New App
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Request type
      options:
        - Bug report
        - Feature request
        - General question
        - Crash / Error
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or request in detail
      placeholder: Tell us what happened or what you'd like to see...
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & iOS Version
      description: If reporting a bug, what device and iOS version?
      placeholder: e.g. iPhone 14 Pro, iOS 17.2
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Which version of the app? (Found in Settings or App Store)
      placeholder: e.g. 1.0.2
    validations:
      required: false
