
import { GoogleGenAI, GenerateContentResponse, Type } from "@google/genai";

export class GeminiService {
  private static getClient() {
    return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  /**
   * Generates a new room design based on an original image and a style.
   */
  static async generateDesign(base64Image: string, styleName: string): Promise<string> {
    const ai = this.getClient();
    const prompt = `Reimagine this room in a high-quality ${styleName} interior design style. Maintain the structural layout and key architectural elements of the room, but replace all furniture, decor, textures, and lighting with ${styleName} aesthetic pieces. The lighting should be professional and atmospheric.`;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image.split(',')[1] || base64Image } },
          { text: prompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by Gemini.");
  }

  /**
   * Edits an existing design based on user text prompt.
   */
  static async editDesign(base64Image: string, editPrompt: string): Promise<string> {
    const ai = this.getClient();
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image.split(',')[1] || base64Image } },
          { text: editPrompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No edited image generated.");
  }

  /**
   * Conversational designer chat for shoppable links and advice.
   */
  static async getDesignAdvice(
    userMessage: string, 
    chatHistory: any[], 
    currentImageBase64?: string
  ): Promise<{ text: string, links: { title: string, uri: string }[] }> {
    const ai = this.getClient();
    
    const parts: any[] = [{ text: userMessage }];
    if (currentImageBase64) {
      parts.push({
        inlineData: {
          mimeType: 'image/jpeg',
          data: currentImageBase64.split(',')[1] || currentImageBase64
        }
      });
    }

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: { parts },
      config: {
        systemInstruction: "You are an expert interior design consultant. Analyze the provided room design image. Provide professional styling advice and suggest shoppable items that would match the vibe. ALWAYS provide grounding links for furniture items mentioned using Google Search grounding.",
        tools: [{ googleSearch: {} }]
      }
    });

    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
    const links = groundingChunks
      .filter((chunk: any) => chunk.web)
      .map((chunk: any) => ({
        title: chunk.web.title,
        uri: chunk.web.uri
      }));

    return {
      text: response.text || "I'm not sure how to respond to that, but the design looks great!",
      links
    };
  }
}
